# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"+\n\x0bTestRequest\x12\r\n\x05name1\x18\x01 \x01(\t\x12\r\n\x05name2\x18\x02 \x01(\x03\"\x1d\n\tTestReply\x12\x10\n\x08message1\x18\x01 \x01(\t2o\n\x07Greeter\x12\x34\n\x08SayHello\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply\"\x00\x12.\n\x04Test\x12\x12.hello.TestRequest\x1a\x10.hello.TestReply\"\x00\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_TESTREQUEST = DESCRIPTOR.message_types_by_name['TestRequest']
_TESTREPLY = DESCRIPTOR.message_types_by_name['TestReply']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQUEST,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.TestRequest)
  })
_sym_db.RegisterMessage(TestRequest)

TestReply = _reflection.GeneratedProtocolMessageType('TestReply', (_message.Message,), {
  'DESCRIPTOR' : _TESTREPLY,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.TestReply)
  })
_sym_db.RegisterMessage(TestReply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=22
  _HELLOREQUEST._serialized_end=50
  _HELLOREPLY._serialized_start=52
  _HELLOREPLY._serialized_end=81
  _TESTREQUEST._serialized_start=83
  _TESTREQUEST._serialized_end=126
  _TESTREPLY._serialized_start=128
  _TESTREPLY._serialized_end=157
  _GREETER._serialized_start=159
  _GREETER._serialized_end=270
# @@protoc_insertion_point(module_scope)
